apiVersion: v1
kind: ServiceAccount
metadata:
  name: grade-service-account
  namespace: grade-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grade-service-account-role
rules:
- nonResourceURLs: ["/*"]
  verbs: ["get", "post"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grade-submission-binding
subjects:
- kind: ServiceAccount
  name: grade-service-account
  namespace: grade-demo
roleRef:
  kind: ClusterRole
  name: grade-service-account-role
  apiGroup: rbac.authorization.k8s.io